# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: &name "Justin Wojciechowski" # &name is a YAML anchor which can be *referenced later
title: Wojo Software LLC
email: justin@wojosoftware.com
description: >- # this means to ignore newlines until "baseurl:"
  This website houses information about myself, Wojo Software LLC, and various
  blogs, articles, documents, etc. that I find valuable and want to share.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wojosoftware.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: "justinwojo/justinwojo.github.io"

minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Build settings
markdown: kramdown
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.14.2"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/justinheadshot.jpg"
  bio              : "Senior Software Engineer with a love for all things Automotive."
  location         : "Eden Prairie, MN"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/justin-wojciechowski/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/justinwojo"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/WuigiBearX"
    - label: "FaceBook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/wojomojo"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/justin-wojciechowski/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/justinwojo"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/WuigiBearX"
    - label: "FaceBook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/wojomojo"

# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Collections
collections:
  software:
    output: true
    permalink: /:collection/:path/
  automotive:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _software
  - scope:
      path: ""
      type: software
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _automotive
  - scope:
      path: ""
      type: automotive
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
